<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	  <title>Enter</title>
	  <meta name="description" content="enter"></meta>
		<? include "include/header.php";	?>
	</head>
	<body>
		<? include "include/top.php";	?>
<div class="group clear">
  <div class="left_col">
    <h1>Evita Slimsonic is a non-invasive treatment which effectively reduces spot fat and cellulite. It uses a new type of advanced ultrasound waves and micro-current massage therapy to melt stubborn body fats safely and naturally in the comfort of your home.</h1>

    <h2>It can reduce large thighs, belly and arms which have previously refused to disappear no matter how much exercise you are doing? The same technology that burns fat also deals with unsightly stretch marks, cellulite and varicose veins? The beauty is it costs no more than a few salon treatments but is effective from the comfort of your own home.</h2>
  
    <br/><br/>

      <h1>Clinically tested and approved for use in the UK, Europe and US.</h1>
      <p>Evita Slimsonic has passed tests and is FDA approved for use in the US and CE Marked for use in the UK and Europe. It is highly effective but also entirely non-invasive and safe. It is clinically tested  and designed to breakdown fats in specific areas only. Combining Ultrasonic Therapy, Heat Therapy and EMS Massage Therapy in one machine, Evita Slimsonic allows you to effectively target specific problem areas and to sculpt your body the way you want it without any side effects.</p>

    <img src="images/evita_before_after_women.png" alt="Slimsonic Before and After" title="Slimsonic Before and After" class="image-col" />
    
    <p><i>"I'm not fat, as you can see from my before photo, but I've stubborn belly fat. No amount of cardio and sit-ups worked. But with Evita Slimsonic, I managed to burn those fats. No more embarrassing belly! Indeed an effective spot fat reduction, super sonic slimming system! Couldn't be happier. Money well spent!"<br/>
Mabel Young</i></p>

    <h2>Evita Slimsonic's benefits include:</h2>
    <p><li>Breakdown stubborn fat cells</li><p>
    <p><li>Reduce cellulite and stretch marks</li><p>
    <p><li>Eliminate waste materials inside your tissue</li><p>
    <p><li>Firm and create an appearance of supple skin</li><p>
    <p><li>Increase the body's metabolism</li><p>
    <p><li>Completely safe and certified</li><p>
    <p><li>No pain or discomfort</li><p>
	  <br/>
	  <p><strong>Additional Benefits:</strong></p>
    <p><li>Encouragement of proper lymphatic functions</li><p>
    <p><li>Enhance permeability of skin surface, allowing for more effective absorption of nutrients and topical creams</li><p>

    <h1>A combination of technologies makes Slimsonic unique!</h1>
    <p>Evita Slimsonic combines 3 functions in one handheld device.</p>
    <p><li>EMS Massage Slimming Therapy</li><p>
    <p><li>Ultrasound Lipolysis Therapy</li><p>
    <p><li>Tissue Repair Heat Therapy</li><p>
  </div>
  <div class="right_col">
    <img src="images/evita_slimaction.jpg" alt="evita slimaction" title="evita slimaction" class="image-col" />

    <p><strong>EMS Massage Therapy</strong></p>
    <p>Evita Slimsonic EMS (Electrical muscle stimulation) Massage Therapy stimulates blood supply and speeds up lymphatic drainage. EMS will stimulate muscle tissue that may not be affected by regular exercise routines.</p>

    <p><strong>Ultrasound Lipolysis Therapy</strong></p>
    <p>Evita Slimsonic's unique ultrasound waves will reach fatty tissues and break them down. The application of Slimaction Slimming Gel on a problem area prior to using the ultrasound is highly recommended. The Gel will help the ultrasound waves to penetrate deep into the fat layer of the skin.</p>

    <p><strong>Tissue Repair Heat Therapy</strong></p>
    <p>Heat generated by Evita Slimsonic LED light penetrates the body tissues gently to revitalize blood vessels and capillaries. It increases blood supply and circulation allowing more oxygen into damaged cells and helping to repair them.</p>

    <h1>Ultrasound Technology</h1>
    <p>Regulated by the FDA and used throughout the UK and Europe. Ultrasound is known to be one of the safest technology used in hospitals, medical practices and treatment therapy.</p>
  <img src="images/Slimsonic_weight_loss.jpg" alt="Slimsonic Weight Loss" title="Slimsonic Weight Loss" class="image-col" />
    <p>Evita Slimsonic represents a new breakthrough for this technology with the highly precise tuning to make spot fat reduction safe. Evita Slimsonic lipolysis system uses advanced ultrasound waves to effectively target and stimulate fat cells into releasing water, free fatty acids, and glycerol (Triglycerides), leaving healthy tissues unharmed. Fat cells shrink significantly, resulting in inch loss for patients.</p>

    <p>The Slimsonic is safe, clinically proven and effective. The Evita Slimsonic is the body wellness system designed to reduce spot fat while improving your body tissues. It is recommended by plastic surgeons as a home use body contouring system.</p>

    <p>The Slimsonic gives you total control in sculpting different areas of your body to attain overall reduction in body circumference. Frequent use of Evita Slimsonic lets you attain your dream shape.</p>

    <p>No downtime or recovery time needed with Evita Slimsonic, allowing you to lose extra inches discretely and conveniently. There is no pain or discomfort with its use either.</p>

    <p>Better yet, you can use it at home, in the office or on vacation, anytime and anywhere you desire. It is discrete and no one has to know your secret behind looking and feeling so good! Be healthy, feel younger and look beautiful.</p>
  </div>
</div>
		<? include "include/footer.php";	?>
	</body>
</html>